name: flutter_puzzle_hack
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  gap: ^2.0.0
  google_fonts: ^2.3.1
  http: ^0.13.4
  intl: ^0.17.0
  image: ^3.1.3
  just_audio: ^0.9.20
  rive: ^0.8.1
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^1.0.0

flutter_gen:
  output: lib/constants/assets/
  integrations:
    flutter_svg: true
    rive: true

# Run below to generate assets
# flutter packages pub run build_runner build

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/icons/
    - assets/images/dash/
    - assets/images/halloween/
    - assets/rive/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
